### ISSUE TITLE
Undefined variable `tanCutWidth`

### ISSUE THREAD

**Issue by unDeadHerbs** [gabrielrobinson000/Openscad-Practice#1]
https://github.com/gabrielrobinson000/Practice-Models-made-in-Openscad/blob/c1f23faeebf538926aad01b205bf15113c546644/library.scad#L70

**Comment by gabrielrobinson000** [comment]
Up dated the function to call the right thing in the library.
29c5e3bb422881136be8eda878410ef392887981

**Comment by unDeadHerbs** [comment]
That variable isn't defined in that function, and `TanCutDepth` isn't used in that function.
