### ISSUE TITLE
Second plate is spaced incorrectly.

### ISSUE THREAD

**Issue by unDeadHerbs** [gabrielrobinson000/Openscad-Practice#3]
I've added a reference ruler next to a projection.
```scad
cube([1,1,15]);
translate([0,0,15+8])
cube([1,1,50]);
translate([0,0,15+16+50])
cube([1,1,15]);

rotate([-90])
projection(cut = true)
rotate([90])
Part_126();
```

https://github.com/gabrielrobinson000/Practice-Models-made-in-Openscad/blob/a6845b53a95516671820abb8472de7c8c9fd9f9e/Practice_Model_126.scad#L27

**Comment by gabrielrobinson000** [comment]
Forgot to add CylHeight to translation to account for plate thickness.
8917034fb3572a3fc9664364143d6226752cefba
